Repository ti-community-infra/devstats, pull requests merged in 2021-04, with the labels that each got.

#5 fix: refine shell file premissions
  configs/dev/chaosmesh/psql.sh
  configs/dev/devel/deploy_all.sh
  configs/dev/devel/get_icon_type.sh
  configs/dev/grafana/chaosmesh/change_title_and_icons.sh
  configs/dev/grafana/chaosmesh/grafana_start.sh
  configs/dev/grafana/tidb/change_title_and_icons.sh
  configs/dev/grafana/tidb/grafana_start.sh
  configs/dev/grafana/tikv/change_title_and_icons.sh
  configs/dev/grafana/tikv/grafana_start.sh
  configs/dev/tidb/psql.sh
  configs/dev/tikv/psql.sh
  deployments/images/build_images.sh
  deployments/images/devstats_reports_docker.sh
  deployments/images/health/static_page_health_check.sh
  deployments/images/patches/make_patch.sh
  deployments/images/patches/patch.sh
  deployments/images/patroni/entrypoint.sh
  deployments/images/remove_images.sh
  deployments/images/test_image_docker.sh
  deployments/images/test_image_kubernetes.sh
Labels: size/XS, status/LGT1, status/can-merge

#9 fix: refine shell scripts permissions
  configs/prod/.keep
  configs/prod/chaosmesh/psql.sh
  configs/prod/devel/deploy_all.sh
  configs/prod/devel/get_icon_type.sh
  configs/prod/grafana/chaosmesh/change_title_and_icons.sh
  configs/prod/grafana/chaosmesh/grafana_start.sh
  configs/prod/grafana/tidb/change_title_and_icons.sh
  configs/prod/grafana/tidb/grafana_start.sh
  configs/prod/grafana/tikv/change_title_and_icons.sh
  configs/prod/grafana/tikv/grafana_start.sh
  configs/prod/tidb/psql.sh
  configs/prod/tikv/psql.sh
Labels: size/XS, status/LGT1, status/can-merge

#11 fix: refine the dashboard links
  configs/dev/grafana/dashboards/chaosmesh/dashboards.json
  configs/dev/grafana/dashboards/tidb/dashboards.json
  configs/dev/grafana/dashboards/tikv/dashboards.json
  configs/dev/metrics/chaosmesh/vars.yaml
  configs/dev/metrics/tidb/vars.yaml
  configs/dev/metrics/tikv/vars.yaml
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/tidb/dashboards.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/metrics/chaosmesh/vars.yaml
  configs/prod/metrics/tidb/vars.yaml
  configs/prod/metrics/tikv/vars.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#10 feat: add dev helm
  deployments/helms/dev/.gitignore
  deployments/helms/dev/.helmignore
  deployments/helms/dev/Chart.yaml
  deployments/helms/dev/secrets/GF_SECURITY_ADMIN_PASSWORD.secret.example
  deployments/helms/dev/secrets/GF_SECURITY_ADMIN_USER.secret.example
  deployments/helms/dev/secrets/GHA2DB_GITHUB_OAUTH.secret.example
  deployments/helms/dev/secrets/PG_ADMIN_USER.secret.example
  deployments/helms/dev/secrets/PG_HOST.secret.example
  deployments/helms/dev/secrets/PG_HOST_RO.secret.example
  deployments/helms/dev/secrets/PG_PASS.secret.example
  deployments/helms/dev/secrets/PG_PASS_REP.secret.example
  deployments/helms/dev/secrets/PG_PASS_RO.secret.example
  deployments/helms/dev/secrets/PG_PASS_TEAM.secret.example
  deployments/helms/dev/secrets/PG_PORT.secret.example
  deployments/helms/dev/templates/_helpers.tpl
  deployments/helms/dev/templates/devstats-bootstrap.yaml
  deployments/helms/dev/templates/devstats-grafana-service.yaml
  deployments/helms/dev/templates/devstats-grafana.yaml
  deployments/helms/dev/templates/devstats-hourly-sync.yaml
  deployments/helms/dev/templates/devstats-ingress.yaml
  deployments/helms/dev/templates/devstats-postgres-endpoint.yaml
  deployments/helms/dev/templates/devstats-postgres-role.yaml
  deployments/helms/dev/templates/devstats-postgres-rolebinding.yaml
  deployments/helms/dev/templates/devstats-postgres-statefulset.yaml
  deployments/helms/dev/templates/devstats-postgres-svc-config.yaml
  deployments/helms/dev/templates/devstats-postgres-svc-ro.yaml
  deployments/helms/dev/templates/devstats-postgres-svc.yaml
  deployments/helms/dev/templates/devstats-postgres-svcacct.yaml
  deployments/helms/dev/templates/devstats-provisions.yaml
  deployments/helms/dev/templates/devstats-pvs.yaml
  deployments/helms/dev/templates/devstats-secrets.yaml
  deployments/helms/dev/templates/devstats-tests.yaml
  deployments/helms/dev/values.yaml
  deployments/helms/prod/.keep
  scripts/switch_namespace.sh
Labels: size/XXL, status/LGT1, status/can-merge

#23 fix: refine the icon and the country label
  configs/dev/grafana/dashboards/chaosmesh/company-prs-in-repository-groups-table.json
  configs/dev/grafana/dashboards/chaosmesh/countries-statistics-in-repository-groups.json
  configs/dev/grafana/dashboards/tidb/company-prs-in-repository-groups-table.json
  configs/dev/grafana/dashboards/tidb/countries-statistics-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/company-prs-in-repository-groups-table.json
  configs/dev/grafana/dashboards/tikv/countries-statistics-in-repository-groups.json
  configs/dev/grafana/img/pingcap.svg
  configs/dev/grafana/img/pingcap32.png
  configs/dev/grafana/img/tidb.svg
  configs/dev/grafana/img/tidb32.png
  configs/dev/grafana/img/tikv32.png
  configs/prod/grafana/dashboards/chaosmesh/company-prs-in-repository-groups-table.json
  configs/prod/grafana/dashboards/chaosmesh/countries-statistics-in-repository-groups.json
  configs/prod/grafana/dashboards/tidb/company-prs-in-repository-groups-table.json
  configs/prod/grafana/dashboards/tidb/countries-statistics-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/company-prs-in-repository-groups-table.json
  configs/prod/grafana/dashboards/tikv/countries-statistics-in-repository-groups.json
  configs/prod/grafana/img/pingcap.svg
  configs/prod/grafana/img/pingcap32.png
  configs/prod/grafana/img/tidb.svg
  configs/prod/grafana/img/tidb32.png
  configs/prod/grafana/img/tikv32.png
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
Labels: size/L, status/LGT1, status/can-merge
