Repository ti-community-infra/devstats, pull requests merged in 2021-06, with the labels that each got.

#60 fix: refine pr opned/closed/merged metrics and dashbaords
  configs/dev/grafana/dashboards/chaosmesh/dashboards.json
  configs/dev/grafana/dashboards/chaosmesh/prs-closed-in-repository-groups.json
  configs/dev/grafana/dashboards/chaosmesh/prs-merged-in-repository-groups.json
  configs/dev/grafana/dashboards/chaosmesh/prs-opened-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/dashboards.json
  configs/dev/grafana/dashboards/pingcap/prs-closed-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/prs-merged-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/prs-opened-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/dashboards.json
  configs/dev/grafana/dashboards/tikv/prs-closed-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/prs-merged-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/prs-opened-in-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/new-prs-in-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/prs-closed-in-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/prs-merged-in-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/prs-merged-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/prs-opened-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/new-prs-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/prs-closed-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/prs-merged-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/prs-merged-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/prs-opened-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/grafana/dashboards/tikv/new-prs-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/prs-closed-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/prs-merged-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/prs-merged-repository-groups.json
  configs/prod/grafana/dashboards/tikv/prs-opened-in-repository-groups.json
  configs/prod/metrics/shared/episodic_contributors.sql
  configs/prod/metrics/shared/metrics.yaml
  configs/prod/metrics/shared/new_contributors.sql
  configs/prod/metrics/shared/pr_closed_company.sql
  configs/prod/metrics/shared/pr_merged_company.sql
  configs/prod/metrics/shared/pr_opened_company.sql
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
  deployments/images/build_images.sh
Labels: size/XXL, status/LGT1, status/can-merge

#62 feat: process the github_users.json file
  tools/affiliations/.env.example
  tools/affiliations/.gitignore
  tools/affiliations/Cargo.lock
  tools/affiliations/importer/Cargo.toml
  tools/affiliations/importer/src/main.rs
Labels: size/XXL, status/LGT1, status/can-merge

#65 feat: upload github_users.json to AWS s3
  tools/affiliations/.env.example
  tools/affiliations/Cargo.lock
  tools/affiliations/importer/Cargo.toml
  tools/affiliations/importer/src/main.rs
Labels: size/XXL, status/LGT1, status/can-merge

#66 docs: update affiliations README.md
  tools/affiliations/README.md
Labels: size/M, status/LGT1, status/can-merge

#64 feat: add affiliations sync cronjob
  configs/dev/devel/db.sh
  configs/dev/devel/drop_by_repos.sh
  configs/dev/devel/drop_psql_db.sh
  configs/dev/devel/drop_ts_tables.sh
  configs/dev/devel/drop_ts_tables_staring_with.sh
  configs/dev/devel/drop_tsdb_affs_tables.sh
  configs/dev/shared/affs.sh
  configs/dev/shared/all_affs.sh
  configs/dev/shared/import_affs.sh
  configs/dev/shared/update_affs.sh
  configs/prod/devel/db.sh
  configs/prod/devel/drop_by_repos.sh
  configs/prod/devel/drop_psql_db.sh
  configs/prod/devel/drop_ts_tables.sh
  configs/prod/devel/drop_ts_tables_staring_with.sh
  configs/prod/devel/drop_tsdb_affs_tables.sh
  configs/prod/shared/affs.sh
  configs/prod/shared/all_affs.sh
  configs/prod/shared/import_affs.sh
  configs/prod/shared/update_affs.sh
  deployments/helms/dev/templates/devstats-affiliations-sync.yaml
  deployments/helms/dev/values.yaml
  deployments/helms/prod/templates/devstats-affiliations-sync.yaml
  deployments/helms/prod/values.yaml
  deployments/images/build_images.sh
Labels: size/XXL, status/LGT1, status/can-merge

#70 fix: fix the grafana image name
  deployments/helms/prod/values.yaml
Labels: size/XS, status/LGT1, status/can-merge

#71 feat: add stale pr table
  configs/dev/metrics/shared/columns.yaml
  configs/dev/metrics/shared/pr_stale_by_sig.sql
  configs/dev/metrics/shared/sig_mentions_labels_sigs_tags.sql
  configs/dev/metrics/shared/sig_mentions_labels_with_non_sigs_tags.sql
  configs/dev/metrics/shared/tags.yaml
  configs/prod/metrics/shared/columns.yaml
  configs/prod/metrics/shared/pr_stale_by_sig.sql
  configs/prod/metrics/shared/sig_mentions_labels_sigs_tags.sql
  configs/prod/metrics/shared/sig_mentions_labels_with_non_sigs_tags.sql
  configs/prod/metrics/shared/tags.yaml
  configs/shared/grafana/chaosmesh/custom_sqlite.sql
  configs/shared/grafana/dashboards/chaosmesh/dashboards.json
  configs/shared/grafana/dashboards/chaosmesh/pr-time-open-to-first-response.json
  configs/shared/grafana/dashboards/chaosmesh/pr-time-opened-to-merged.json
  configs/shared/grafana/dashboards/chaosmesh/stale-pr-table.json
  configs/shared/grafana/dashboards/chaosmesh/stale-prs-by-sig.json
  configs/shared/grafana/dashboards/pingcap/dashboards.json
  configs/shared/grafana/dashboards/pingcap/pr-time-open-to-first-response.json
  configs/shared/grafana/dashboards/pingcap/pr-time-opened-to-merged.json
  configs/shared/grafana/dashboards/pingcap/stale-pr-table.json
  configs/shared/grafana/dashboards/pingcap/stale-prs-by-sig.json
  configs/shared/grafana/dashboards/tikv/dashboards.json
  configs/shared/grafana/dashboards/tikv/pr-time-open-to-first-response.json
  configs/shared/grafana/dashboards/tikv/pr-time-opened-to-merged.json
  configs/shared/grafana/dashboards/tikv/stale-pr-table.json
  configs/shared/grafana/dashboards/tikv/stale-prs-by-sig.json
  configs/shared/grafana/pingcap/custom_sqlite.sql
  configs/shared/grafana/tikv/custom_sqlite.sql
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
Labels: size/XXL, status/LGT1, status/can-merge
