Repository ti-community-infra/devstats, pull requests merged in 2021-05, with the labels that each got.

#25 feat: add contributor profile dashboard
  .gitignore
  configs/dev/grafana/dashboards/chaosmesh/contributor-profile.json
  configs/dev/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/pingcap/contributor-profile.json
  configs/dev/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/tidb/contributor-profile.json
  configs/dev/grafana/dashboards/tidb/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/tikv/contributor-profile.json
  configs/dev/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
  configs/dev/metrics/shared/all_user_activity.sql
  configs/dev/metrics/shared/all_user_activity_commits.sql
  configs/dev/metrics/shared/all_user_activity_issues.sql
  configs/dev/metrics/shared/all_user_activity_prs.sql
  configs/dev/metrics/shared/all_users_tags.sql
  configs/dev/metrics/shared/columns.yaml
  configs/dev/metrics/shared/metrics.yaml
  configs/dev/metrics/shared/tags.yaml
  configs/dev/pingcap/psql.sh
  configs/dev/projects.yaml
  configs/dev/test/data/test_columns.yaml
  configs/dev/test/data/test_metrics.yaml
  configs/dev/test/data/test_tags.yaml
  configs/dev/test/test_metric_sync.sh
  configs/dev/test/test_tags.sh
  configs/dev/util_sql/exclude_bots.sql
  deployments/helms/dev/values.yaml
Labels: size/XXL

#29 docs: init book
  docs/.gitignore
  docs/book.toml
  docs/src/SUMMARY.md
  docs/src/dashboards/chaosmesh/.keep
  docs/src/dashboards/pingcap/.keep
  docs/src/dashboards/shared/.keep
  docs/src/dashboards/tikv/.keep
  docs/src/introduction.md
Labels: size/S, status/LGT1, status/can-merge

#32 fix: fix rerun failure problem
  configs/dev/devel/create_databases.sh
  configs/prod/devel/create_databases.sh
Labels: size/L, status/LGT1, status/can-merge

#35 feat: add not-pingcap filter option and chart
  configs/dev/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/pingcap/company-statistics-by-repository-group.json
  configs/dev/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/pingcap/documentation-committers-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/prs-authors-repository-groups.json
  configs/dev/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
  deployments/helms/dev/values.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#37 config: bump version to 0.2.0 and update some helm configs
  deployments/helms/dev/templates/devstats-provisions.yaml
  deployments/helms/dev/values.yaml
  deployments/helms/prod/templates/devstats-provisions.yaml
  deployments/helms/prod/values.yaml
Labels: size/S, status/LGT1, status/can-merge

#38 feat: add execute command pod and update values
  deployments/helms/dev/templates/devstats-execute.yaml
  deployments/helms/dev/templates/devstats-hourly-sync.yaml
  deployments/helms/dev/templates/devstats-provisions.yaml
  deployments/helms/dev/values.yaml
  deployments/helms/prod/templates/devstats-execute.yaml
  deployments/helms/prod/templates/devstats-hourly-sync.yaml
  deployments/helms/prod/templates/devstats-provisions.yaml
  deployments/helms/prod/values.yaml
Labels: size/XL, status/LGT1, status/can-merge

#47 fix: refine some links and names
  configs/dev/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
Labels: size/M, status/LGT1, status/can-merge

#46 feat: add company group for pr lifecycle related metrics
  configs/dev/grafana/dashboards/chaosmesh/open-pr-age-by-repository-group.json
  configs/dev/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/dev/grafana/dashboards/chaosmesh/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/chaosmesh/time-to-merge-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/open-pr-age-by-repository-group.json
  configs/dev/grafana/dashboards/pingcap/opened-to-merged.json
  configs/dev/grafana/dashboards/pingcap/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/pingcap/time-to-merge-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/open-pr-age-by-repository-group.json
  configs/dev/grafana/dashboards/tikv/opened-to-merged.json
  configs/dev/grafana/dashboards/tikv/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/tikv/time-to-merge-in-repository-groups.json
  configs/dev/metrics/shared/metrics.yaml
  configs/dev/metrics/shared/pr_age_company.sql
  configs/dev/metrics/shared/pr_first_non_author_activity_company.sql
  configs/dev/metrics/shared/pr_opened_to_merged_company.sql
  configs/dev/metrics/shared/pr_time_metric_company.sql
  configs/dev/test/data/test_metrics.yaml
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/open-pr-age-by-repository-group.json
  configs/prod/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/prod/grafana/dashboards/chaosmesh/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/chaosmesh/time-to-merge-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/open-pr-age-by-repository-group.json
  configs/prod/grafana/dashboards/pingcap/opened-to-merged.json
  configs/prod/grafana/dashboards/pingcap/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/pingcap/time-to-merge-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/grafana/dashboards/tikv/open-pr-age-by-repository-group.json
  configs/prod/grafana/dashboards/tikv/opened-to-merged.json
  configs/prod/grafana/dashboards/tikv/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/tikv/time-to-merge-in-repository-groups.json
  configs/prod/metrics/chaosmesh/vars.yaml
  configs/prod/metrics/pingcap/vars.yaml
  configs/prod/metrics/shared/metrics.yaml
  configs/prod/metrics/shared/pr_age_company.sql
  configs/prod/metrics/shared/pr_first_non_author_activity_company.sql
  configs/prod/metrics/shared/pr_opened_to_merged_company.sql
  configs/prod/metrics/shared/pr_time_metric_company.sql
  configs/prod/metrics/tikv/vars.yaml
  deployments/helms/dev/values.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#50 feat: add active dashboards
  configs/dev/grafana/dashboards/chaosmesh/contributor-profile.json
  configs/dev/grafana/dashboards/chaosmesh/dashboards.json
  configs/dev/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/chaosmesh/open-pr-age-by-repository-group.json
  configs/dev/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/dev/grafana/dashboards/chaosmesh/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/chaosmesh/time-to-merge-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/contributor-profile.json
  configs/dev/grafana/dashboards/pingcap/dashboards.json
  configs/dev/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/pingcap/open-pr-age-by-repository-group.json
  configs/dev/grafana/dashboards/pingcap/opened-to-merged.json
  configs/dev/grafana/dashboards/pingcap/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/pingcap/time-to-merge-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/contributor-profile.json
  configs/dev/grafana/dashboards/tikv/dashboards.json
  configs/dev/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/tikv/open-pr-age-by-repository-group.json
  configs/dev/grafana/dashboards/tikv/opened-to-merged.json
  configs/dev/grafana/dashboards/tikv/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/tikv/time-to-merge-in-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/contributor-profile.json
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/chaosmesh/open-pr-age-by-repository-group.json
  configs/prod/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/prod/grafana/dashboards/chaosmesh/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/pingcap/contributor-profile.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/pingcap/open-pr-age-by-repository-group.json
  configs/prod/grafana/dashboards/pingcap/opened-to-merged.json
  configs/prod/grafana/dashboards/pingcap/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/tikv/contributor-profile.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/tikv/open-pr-age-by-repository-group.json
  configs/prod/grafana/dashboards/tikv/opened-to-merged.json
  configs/prod/grafana/dashboards/tikv/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/tikv/time-to-merge-in-repository-groups.json
  deployments/helms/dev/values.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#51 build: bump all version to 0.2.2
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
Labels: size/M, status/LGT1, status/can-merge

#52 fix: fix the broken link for prod and bump to 0.2.3
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/time-to-merge-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/time-to-merge-in-repository-groups.json
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
Labels: size/M, status/LGT1, status/can-merge

#49 feat: support list all github logins
  tools/affiliations/.env.example
  tools/affiliations/crawler/Cargo.toml
  tools/affiliations/crawler/src/auth.rs
  tools/affiliations/crawler/src/crawler.rs
  tools/affiliations/crawler/src/departments.rs
  tools/affiliations/crawler/src/lark.rs
  tools/affiliations/crawler/src/lib.rs
  tools/affiliations/crawler/src/resp.rs
  tools/affiliations/crawler/src/users.rs
  tools/affiliations/importer/Cargo.toml
  tools/affiliations/importer/src/main.rs
Labels: size/XL, status/LGT1, status/can-merge

#53 feat: add issue lifecycle related metrics
  configs/dev/grafana/chaosmesh/custom_sqlite.sql
  configs/dev/grafana/dashboards/chaosmesh/dashboards.json
  configs/dev/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/chaosmesh/issue-time-to-first-comment.json
  configs/dev/grafana/dashboards/chaosmesh/issues-age-by-repository-group.json
  configs/dev/grafana/dashboards/pingcap/dashboards.json
  configs/dev/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/pingcap/issue-time-to-first-comment.json
  configs/dev/grafana/dashboards/pingcap/issues-age-by-repository-group.json
  configs/dev/grafana/dashboards/tikv/dashboards.json
  configs/dev/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
  configs/dev/grafana/dashboards/tikv/issue-time-to-first-comment.json
  configs/dev/grafana/dashboards/tikv/issues-age-by-repository-group.json
  configs/dev/grafana/pingcap/custom_sqlite.sql
  configs/dev/grafana/tikv/custom_sqlite.sql
  configs/dev/metrics/shared/issue_age_company.sql
  configs/dev/metrics/shared/issue_first_comment_time_company.sql
  configs/dev/metrics/shared/metrics.yaml
  configs/dev/test/data/test_metrics.yaml
  configs/prod/grafana/chaosmesh/custom_sqlite.sql
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/chaosmesh/issue-time-to-first-comment.json
  configs/prod/grafana/dashboards/chaosmesh/issues-age-by-repository-group.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/pingcap/issue-time-to-first-comment.json
  configs/prod/grafana/dashboards/pingcap/issues-age-by-repository-group.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/grafana/dashboards/tikv/developer-activity-counts-by-companies.json
  configs/prod/grafana/dashboards/tikv/issue-time-to-first-comment.json
  configs/prod/grafana/dashboards/tikv/issues-age-by-repository-group.json
  configs/prod/grafana/pingcap/custom_sqlite.sql
  configs/prod/grafana/tikv/custom_sqlite.sql
  configs/prod/metrics/shared/issue_age_company.sql
  configs/prod/metrics/shared/issue_first_comment_time_company.sql
  configs/prod/metrics/shared/metrics.yaml
  deployments/helms/dev/values.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#54 build: bump devstats version to 0.2.4
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
Labels: size/S, status/LGT1, status/can-merge

#56 fix: fix the wrong compare chart
  configs/dev/grafana/dashboards/chaosmesh/dashboards.json
  configs/dev/grafana/dashboards/chaosmesh/issue-time-to-first-comment.json
  configs/dev/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/dev/grafana/dashboards/chaosmesh/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/pingcap/dashboards.json
  configs/dev/grafana/dashboards/pingcap/issue-time-to-first-comment.json
  configs/dev/grafana/dashboards/pingcap/opened-to-merged.json
  configs/dev/grafana/dashboards/pingcap/pr-time-to-engagement.json
  configs/dev/grafana/dashboards/tikv/dashboards.json
  configs/dev/grafana/dashboards/tikv/issue-time-to-first-comment.json
  configs/dev/grafana/dashboards/tikv/opened-to-merged.json
  configs/dev/grafana/dashboards/tikv/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/issue-time-to-first-comment.json
  configs/prod/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/prod/grafana/dashboards/chaosmesh/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/issue-time-to-first-comment.json
  configs/prod/grafana/dashboards/pingcap/opened-to-merged.json
  configs/prod/grafana/dashboards/pingcap/pr-time-to-engagement.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/grafana/dashboards/tikv/issue-time-to-first-comment.json
  configs/prod/grafana/dashboards/tikv/opened-to-merged.json
  configs/prod/grafana/dashboards/tikv/pr-time-to-engagement.json
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
Labels: size/XL, status/LGT1, status/can-merge

#57 feat: support tls
  configs/dev/grafana/dashboards/chaosmesh/dashboards.json
  configs/dev/grafana/dashboards/pingcap/dashboards.json
  configs/dev/grafana/dashboards/tikv/dashboards.json
  configs/dev/metrics/chaosmesh/vars.yaml
  configs/dev/metrics/pingcap/vars.yaml
  configs/dev/metrics/tikv/vars.yaml
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  deployments/helms/dev/templates/devstats-ingress.yaml
  deployments/helms/dev/values.yaml
  deployments/helms/prod/templates/devstats-ingress.yaml
Labels: size/L, status/LGT1, status/can-merge

#59 feat: add company and bot group for PR/contributor metrics
  configs/dev/grafana/chaosmesh/custom_sqlite.sql
  configs/dev/grafana/dashboards/chaosmesh/dashboards.json
  configs/dev/grafana/dashboards/chaosmesh/new-and-episodic-pr-contributors.json
  configs/dev/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/dev/grafana/dashboards/chaosmesh/prs-closed-in-repository-groups.json
  configs/dev/grafana/dashboards/chaosmesh/prs-merged-in-repository-groups.json
  configs/dev/grafana/dashboards/chaosmesh/prs-opened-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/dashboards.json
  configs/dev/grafana/dashboards/pingcap/new-and-episodic-pr-contributors.json
  configs/dev/grafana/dashboards/pingcap/opened-to-merged.json
  configs/dev/grafana/dashboards/pingcap/prs-closed-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/prs-merged-in-repository-groups.json
  configs/dev/grafana/dashboards/pingcap/prs-opened-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/dashboards.json
  configs/dev/grafana/dashboards/tikv/new-and-episodic-pr-contributors.json
  configs/dev/grafana/dashboards/tikv/opened-to-merged.json
  configs/dev/grafana/dashboards/tikv/prs-closed-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/prs-merged-in-repository-groups.json
  configs/dev/grafana/dashboards/tikv/prs-merged-repository-groups.json
  configs/dev/grafana/dashboards/tikv/prs-opened-in-repository-groups.json
  configs/dev/grafana/pingcap/custom_sqlite.sql
  configs/dev/grafana/tikv/custom_sqlite.sql
  configs/dev/metrics/shared/episodic_contributors.sql
  configs/dev/metrics/shared/metrics.yaml
  configs/dev/metrics/shared/new_contributors.sql
  configs/dev/metrics/shared/pr_closed_company.sql
  configs/dev/metrics/shared/pr_merged_company.sql
  configs/dev/metrics/shared/pr_opened_company.sql
  configs/dev/test/data/test_metrics.yaml
  configs/prod/grafana/chaosmesh/custom_sqlite.sql
  configs/prod/grafana/dashboards/chaosmesh/dashboards.json
  configs/prod/grafana/dashboards/chaosmesh/new-and-episodic-pr-contributors.json
  configs/prod/grafana/dashboards/chaosmesh/opened-to-merged.json
  configs/prod/grafana/dashboards/chaosmesh/prs-closed-in-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/prs-merged-in-repository-groups.json
  configs/prod/grafana/dashboards/chaosmesh/prs-opened-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/dashboards.json
  configs/prod/grafana/dashboards/pingcap/new-and-episodic-pr-contributors.json
  configs/prod/grafana/dashboards/pingcap/opened-to-merged.json
  configs/prod/grafana/dashboards/pingcap/prs-closed-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/prs-merged-in-repository-groups.json
  configs/prod/grafana/dashboards/pingcap/prs-opened-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/dashboards.json
  configs/prod/grafana/dashboards/tikv/new-and-episodic-pr-contributors.json
  configs/prod/grafana/dashboards/tikv/opened-to-merged.json
  configs/prod/grafana/dashboards/tikv/prs-closed-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/prs-merged-in-repository-groups.json
  configs/prod/grafana/dashboards/tikv/prs-opened-in-repository-groups.json
  configs/prod/grafana/pingcap/custom_sqlite.sql
  configs/prod/grafana/tikv/custom_sqlite.sql
  deployments/helms/dev/values.yaml
  deployments/helms/prod/values.yaml
Labels: size/XXL, status/LGT1, status/can-merge
